ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "annualPersonalIncomeUsd" DOUBLE PRECISION;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "biologicalSex" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "ethnicityOrRace" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "maritalStatus" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "numberOfDependents" INTEGER;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "primaryLanguage" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "healthInsuranceType" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "chronicConditionCount" INTEGER;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "disabilityStatus" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "smokingStatus" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "alcoholFrequency" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "heightCm" DOUBLE PRECISION;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "annualTaxesPaidUsd" DOUBLE PRECISION;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "monthlyHousingCostUsd" DOUBLE PRECISION;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "housingStatus" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "hoursWorkedPerWeek" INTEGER;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "industryOrSector" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "citizenshipStatus" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "internetAccessType" TEXT;

CREATE INDEX IF NOT EXISTS "User_annualPersonalIncomeUsd_idx"
ON "User"("annualPersonalIncomeUsd");
