import type { BudgetCategoryId } from "@/lib/wishocracy-data";

export interface AlignmentBillFeedConfig {
  billType?: string;
  limit: number;
}

export interface AlignmentLegislativeCategoryRule {
  categoryId: BudgetCategoryId;
  keywords: readonly string[];
  policyAreas?: readonly string[];
}

const RECENT_BILLS_PER_CONGRESS = 100;
const RECENT_HOUSE_RESOLUTIONS_PER_CONGRESS = 40;
const RECENT_HOUSE_JOINT_RESOLUTIONS_PER_CONGRESS = 25;
const RECENT_SENATE_BILLS_PER_CONGRESS = 60;
const RECENT_SENATE_RESOLUTIONS_PER_CONGRESS = 30;
const RECENT_SENATE_JOINT_RESOLUTIONS_PER_CONGRESS = 25;

export const ALIGNMENT_BILL_FEEDS: readonly AlignmentBillFeedConfig[] = [
  { limit: RECENT_BILLS_PER_CONGRESS },
  { billType: "hres", limit: RECENT_HOUSE_RESOLUTIONS_PER_CONGRESS },
  { billType: "hjres", limit: RECENT_HOUSE_JOINT_RESOLUTIONS_PER_CONGRESS },
  { billType: "s", limit: RECENT_SENATE_BILLS_PER_CONGRESS },
  { billType: "sres", limit: RECENT_SENATE_RESOLUTIONS_PER_CONGRESS },
  { billType: "sjres", limit: RECENT_SENATE_JOINT_RESOLUTIONS_PER_CONGRESS },
] as const;

export const ALIGNMENT_LEGISLATIVE_CATEGORY_RULES: readonly AlignmentLegislativeCategoryRule[] = [
  {
    categoryId: "PRAGMATIC_CLINICAL_TRIALS",
    keywords: [
      "agency for healthcare research and quality",
      "ahrq",
      "arpa h",
      "arpa-h",
      "biomedical research",
      "cancer research",
      "clinical research",
      "clinical trial",
      "comparative effectiveness",
      "health services research",
      "medical research",
      "national institutes of health",
      "nih",
      "patient centered outcomes research",
      "patient-centered outcomes research",
      "pcori",
      "research administration and funding",
    ],
    policyAreas: ["health", "science", "technology"],
  },
  {
    categoryId: "ADDICTION_TREATMENT",
    keywords: [
      "addiction treatment",
      "behavioral health",
      "behavioral health services",
      "behavioral health treatment",
      "buprenorphine",
      "medication assisted treatment",
      "medication-assisted treatment",
      "mental health and substance use services",
      "methadone",
      "naloxone",
      "opioid treatment",
      "overdose prevention",
      "recovery",
      "recovery support service",
      "samhsa",
      "substance abuse treatment",
      "substance misuse",
      "substance use disorder",
      "syringe services",
    ],
    policyAreas: ["families", "health", "drugs"],
  },
  {
    categoryId: "EARLY_CHILDHOOD_EDUCATION",
    keywords: [
      "child care",
      "child care and development",
      "child care and development block grant",
      "child care assistance",
      "child care provider",
      "child care workforce",
      "childcare",
      "day care",
      "early childhood",
      "early head start",
      "early learning",
      "family literacy",
      "head start",
      "pre kindergarten",
      "pre-kindergarten",
      "prekindergarten",
      "preschool",
      "school readiness",
    ],
    policyAreas: ["children", "education", "families"],
  },
  {
    categoryId: "DRUG_WAR_ENFORCEMENT",
    keywords: [
      "counter narcotics",
      "counter-narcotics",
      "dea",
      "drug control",
      "drug control policy",
      "drug enforcement",
      "drug free communities",
      "drug trafficking",
      "drug trafficking and controlled substances",
      "drug interdiction",
      "drug smuggling",
      "high intensity drug trafficking area",
      "high intensity drug trafficking areas",
      "hidta",
      "narcotics control",
      "office of national drug control policy",
      "ondcp",
    ],
    policyAreas: ["crime and law enforcement", "drugs"],
  },
  {
    categoryId: "ICE_IMMIGRATION_ENFORCEMENT",
    keywords: [
      "alien gang",
      "border patrol",
      "border security",
      "customs and border protection",
      "cbp",
      "deportable alien",
      "detention bed",
      "detention center",
      "detention of persons",
      "detention facility",
      "deportation",
      "e verify",
      "e-verify",
      "ice detention",
      "immigration and customs enforcement",
      "immigration detention",
      "immigration enforcement",
      "migrant crime",
      "removable alien",
      "removal proceedings",
      "sanctuary city",
      "unlawful immigration",
      "visa overstay",
      "mega center",
      "mega-center",
      "warehouse detention",
      "detention expansion",
      "mass deportation",
      "processing center",
      "detention bed capacity",
    ],
    policyAreas: ["crime and law enforcement", "immigration"],
  },
  {
    categoryId: "FARM_SUBSIDIES_AGRIBUSINESS",
    keywords: [
      "agricultural subsidy",
      "agribusiness",
      "agriculture risk coverage",
      "commodity credit corporation",
      "commodity programs",
      "commodity support",
      "crop insurance",
      "dairy margin coverage",
      "farm bill",
      "farm credit",
      "farm service agency",
      "farm subsidy",
      "farm support",
      "federal crop insurance",
      "livestock indemnity",
      "price loss coverage",
    ],
    policyAreas: ["agriculture and food"],
  },
  {
    categoryId: "FOSSIL_FUEL_SUBSIDIES",
    keywords: [
      "coal",
      "drilling",
      "fossil energy",
      "fossil fuel",
      "fossil fuel infrastructure",
      "fracking",
      "gas export",
      "lng",
      "liquefied natural gas",
      "natural gas export",
      "offshore drilling",
      "offshore oil",
      "offshore leasing",
      "oil and gas",
      "oil leasing",
      "petroleum",
      "pipeline",
      "royalty relief",
    ],
    policyAreas: ["energy", "environmental protection"],
  },
  {
    categoryId: "NUCLEAR_WEAPONS_MODERNIZATION",
    keywords: [
      "b61",
      "ballistic missile",
      "columbia class",
      "icbm",
      "missile silo",
      "national nuclear security administration",
      "nuclear command",
      "nuclear command control and communications",
      "nuclear deterrence",
      "nuclear modernization",
      "nuclear triad",
      "nuclear weapon",
      "plutonium pit",
      "sea launched cruise missile",
      "sea-launched cruise missile",
      "sentinel",
      "strategic deterrent",
      "strategic forces",
      "trident",
      "uranium processing facility",
      "warhead",
    ],
    policyAreas: ["armed forces and national security"],
  },
  {
    categoryId: "PRISON_CONSTRUCTION",
    keywords: [
      "bureau of prisons",
      "correctional facility",
      "correctional facilities",
      "correctional infrastructure",
      "correctional officer",
      "corrections officer",
      "detention facility",
      "detention facilities",
      "federal prison",
      "jail construction",
      "jail expansion",
      "jail staffing",
      "prison construction",
      "prison expansion",
      "prison staffing",
    ],
    policyAreas: ["crime and law enforcement"],
  },
  {
    categoryId: "MILITARY_OPERATIONS",
    keywords: [
      "air force",
      "aircraft carrier",
      "armed forces",
      "armed services",
      "arms sale",
      "army",
      "combat aircraft",
      "defense appropriation",
      "defense appropriations",
      "defense articles and services",
      "defense authorization",
      "fighter aircraft",
      "foreign military financing",
      "foreign military sale",
      "military facilities",
      "military operation",
      "military procurement",
      "missile defense",
      "missile procurement",
      "munitions",
      "national defense authorization act",
      "navy",
      "ndaa",
      "pentagon",
      "shipbuilding",
      "weapons development",
      "weapons system",
    ],
    policyAreas: ["armed forces and national security"],
  },
] as const;
