import type { WishocraticItemId } from "@/lib/wishocracy-data";

export interface AlignmentBillFeedConfig {
  billType?: string;
  limit: number;
}

export interface AlignmentLegislativeCategoryRule {
  categoryId: WishocraticItemId;
  keywords: readonly string[];
  policyAreas?: readonly string[];
}

const RECENT_BILLS_PER_CONGRESS = 100;
const RECENT_HOUSE_RESOLUTIONS_PER_CONGRESS = 40;
const RECENT_HOUSE_JOINT_RESOLUTIONS_PER_CONGRESS = 25;
const RECENT_SENATE_BILLS_PER_CONGRESS = 60;
const RECENT_SENATE_RESOLUTIONS_PER_CONGRESS = 30;
const RECENT_SENATE_JOINT_RESOLUTIONS_PER_CONGRESS = 25;

export const ALIGNMENT_BILL_FEEDS: readonly AlignmentBillFeedConfig[] = [
  { limit: RECENT_BILLS_PER_CONGRESS },
  { billType: "hres", limit: RECENT_HOUSE_RESOLUTIONS_PER_CONGRESS },
  { billType: "hjres", limit: RECENT_HOUSE_JOINT_RESOLUTIONS_PER_CONGRESS },
  { billType: "s", limit: RECENT_SENATE_BILLS_PER_CONGRESS },
  { billType: "sres", limit: RECENT_SENATE_RESOLUTIONS_PER_CONGRESS },
  { billType: "sjres", limit: RECENT_SENATE_JOINT_RESOLUTIONS_PER_CONGRESS },
] as const;

export const ALIGNMENT_LEGISLATIVE_CATEGORY_RULES: readonly AlignmentLegislativeCategoryRule[] = [
  {
    categoryId: "PRAGMATIC_CLINICAL_TRIALS",
    keywords: [
      "agency for healthcare research and quality",
      "ahrq",
      "arpa h",
      "arpa-h",
      "biomedical research",
      "cancer research",
      "clinical research",
      "clinical trial",
      "comparative effectiveness",
      "health services research",
      "medical research",
      "national institutes of health",
      "nih",
      "patient centered outcomes research",
      "patient-centered outcomes research",
      "pcori",
      "research administration and funding",
    ],
    policyAreas: ["health", "science", "technology"],
  },
  {
    categoryId: "ADDICTION_TREATMENT",
    keywords: [
      "addiction treatment",
      "behavioral health",
      "behavioral health services",
      "behavioral health treatment",
      "buprenorphine",
      "medication assisted treatment",
      "medication-assisted treatment",
      "mental health and substance use services",
      "methadone",
      "naloxone",
      "opioid treatment",
      "overdose prevention",
      "recovery",
      "recovery support service",
      "samhsa",
      "substance abuse treatment",
      "substance misuse",
      "substance use disorder",
      "syringe services",
    ],
    policyAreas: ["families", "health", "drugs"],
  },
  {
    categoryId: "EARLY_CHILDHOOD_EDUCATION",
    keywords: [
      "child care",
      "child care and development",
      "child care and development block grant",
      "child care assistance",
      "child care provider",
      "child care workforce",
      "childcare",
      "day care",
      "early childhood",
      "early head start",
      "early learning",
      "family literacy",
      "head start",
      "pre kindergarten",
      "pre-kindergarten",
      "prekindergarten",
      "preschool",
      "school readiness",
    ],
    policyAreas: ["children", "education", "families"],
  },
  {
    categoryId: "DRUG_WAR_ENFORCEMENT",
    keywords: [
      "counter narcotics",
      "counter-narcotics",
      "dea",
      "drug control",
      "drug control policy",
      "drug enforcement",
      "drug free communities",
      "drug trafficking",
      "drug trafficking and controlled substances",
      "drug interdiction",
      "drug smuggling",
      "high intensity drug trafficking area",
      "high intensity drug trafficking areas",
      "hidta",
      "narcotics control",
      "office of national drug control policy",
      "ondcp",
    ],
    policyAreas: ["crime and law enforcement", "drugs"],
  },
  {
    categoryId: "ICE_IMMIGRATION_ENFORCEMENT",
    keywords: [
      "alien gang",
      "border patrol",
      "border security",
      "customs and border protection",
      "cbp",
      "deportable alien",
      "detention bed",
      "detention center",
      "detention of persons",
      "detention facility",
      "deportation",
      "e verify",
      "e-verify",
      "ice detention",
      "immigration and customs enforcement",
      "immigration detention",
      "immigration enforcement",
      "migrant crime",
      "removable alien",
      "removal proceedings",
      "sanctuary city",
      "unlawful immigration",
      "visa overstay",
      "mega center",
      "mega-center",
      "warehouse detention",
      "detention expansion",
      "mass deportation",
      "processing center",
      "detention bed capacity",
    ],
    policyAreas: ["crime and law enforcement", "immigration"],
  },
  {
    categoryId: "FARM_SUBSIDIES_AGRIBUSINESS",
    keywords: [
      "agricultural subsidy",
      "agribusiness",
      "agriculture risk coverage",
      "commodity credit corporation",
      "commodity programs",
      "commodity support",
      "crop insurance",
      "dairy margin coverage",
      "farm bill",
      "farm credit",
      "farm service agency",
      "farm subsidy",
      "farm support",
      "federal crop insurance",
      "livestock indemnity",
      "price loss coverage",
    ],
    policyAreas: ["agriculture and food"],
  },
  {
    categoryId: "FOSSIL_FUEL_SUBSIDIES",
    keywords: [
      "coal",
      "drilling",
      "fossil energy",
      "fossil fuel",
      "fossil fuel infrastructure",
      "fracking",
      "gas export",
      "lng",
      "liquefied natural gas",
      "natural gas export",
      "offshore drilling",
      "offshore oil",
      "offshore leasing",
      "oil and gas",
      "oil leasing",
      "petroleum",
      "pipeline",
      "royalty relief",
    ],
    policyAreas: ["energy", "environmental protection"],
  },
  {
    categoryId: "NUCLEAR_WEAPONS_MODERNIZATION",
    keywords: [
      "b61",
      "ballistic missile",
      "columbia class",
      "icbm",
      "missile silo",
      "national nuclear security administration",
      "nuclear command",
      "nuclear command control and communications",
      "nuclear deterrence",
      "nuclear modernization",
      "nuclear triad",
      "nuclear weapon",
      "plutonium pit",
      "sea launched cruise missile",
      "sea-launched cruise missile",
      "sentinel",
      "strategic deterrent",
      "strategic forces",
      "trident",
      "uranium processing facility",
      "warhead",
    ],
    policyAreas: ["armed forces and national security"],
  },
  {
    categoryId: "PRISON_CONSTRUCTION",
    keywords: [
      "bureau of prisons",
      "correctional facility",
      "correctional facilities",
      "correctional infrastructure",
      "correctional officer",
      "corrections officer",
      "detention facility",
      "detention facilities",
      "federal prison",
      "jail construction",
      "jail expansion",
      "jail staffing",
      "prison construction",
      "prison expansion",
      "prison staffing",
    ],
    policyAreas: ["crime and law enforcement"],
  },
  {
    categoryId: "MILITARY_OPERATIONS",
    keywords: [
      "air force",
      "aircraft carrier",
      "armed forces",
      "armed services",
      "arms sale",
      "army",
      "combat aircraft",
      "defense appropriation",
      "defense appropriations",
      "defense articles and services",
      "defense authorization",
      "fighter aircraft",
      "foreign military financing",
      "foreign military sale",
      "military facilities",
      "military operation",
      "military procurement",
      "missile defense",
      "missile procurement",
      "munitions",
      "national defense authorization act",
      "navy",
      "ndaa",
      "pentagon",
      "shipbuilding",
      "weapons development",
      "weapons system",
    ],
    policyAreas: ["armed forces and national security"],
  },
  {
    categoryId: "BOMBING_IRAN",
    keywords: [
      "iran war",
      "iran military",
      "iran strike",
      "iran sanctions",
      "operation epic fury",
      "persian gulf",
      "strait of hormuz",
      "iran regime",
      "iran nuclear",
      "middle east military",
      "war powers resolution iran",
      "aumf iran",
      "authorization military force iran",
      "iran supplemental",
    ],
    policyAreas: ["armed forces and national security", "international affairs"],
  },
  {
    categoryId: "ISRAEL_GAZA_MILITARY_AID",
    keywords: [
      "israel military aid",
      "israel defense",
      "iron dome",
      "israel security assistance",
      "foreign military financing israel",
      "gaza",
      "israel arms",
      "israel munitions",
      "qualitative military edge",
      "memorandum of understanding israel",
      "israel supplemental",
    ],
    policyAreas: ["armed forces and national security", "international affairs"],
  },
  {
    categoryId: "YEMEN_HOUTHI_STRIKES",
    keywords: [
      "houthi",
      "yemen strike",
      "red sea",
      "operation rough rider",
      "bab el mandeb",
      "yemen military",
      "ansar allah",
      "red sea shipping",
      "yemen naval",
    ],
    policyAreas: ["armed forces and national security", "international affairs"],
  },
  {
    categoryId: "CORPORATE_WELFARE",
    keywords: [
      "corporate subsidy",
      "corporate tax break",
      "business incentive",
      "economic development grant",
      "export-import bank",
      "industrial subsidy",
      "government guarantee",
      "loan guarantee program",
      "tax expenditure",
      "investment tax credit",
      "opportunity zone",
      "carried interest",
      "accelerated depreciation",
      "corporate bailout",
      "too big to fail",
    ],
    policyAreas: ["economics and public finance", "taxation", "commerce"],
  },
  {
    categoryId: "AI_MASS_SURVEILLANCE",
    keywords: [
      "mass surveillance",
      "domestic surveillance",
      "warrantless surveillance",
      "facial recognition",
      "social media monitoring",
      "predictive policing",
      "ai surveillance",
      "section 702",
      "fisa",
      "signals intelligence",
      "data collection program",
      "biometric surveillance",
      "surveillance technology",
      "automated decision",
    ],
    policyAreas: [
      "government operations and politics",
      "civil rights and liberties, minority issues",
      "science, technology, communications",
    ],
  },
  {
    categoryId: "CYBERSECURITY",
    keywords: [
      "cisa",
      "cyber command",
      "cyber incident",
      "cyber threat",
      "cybersecurity",
      "critical infrastructure protection",
      "data breach",
      "data breach notification",
      "election security",
      "federal information security",
      "fisma",
      "grid security",
      "information assurance",
      "network security",
      "ransomware",
      "supply chain security",
      "vulnerability disclosure",
      "zero day",
      "zero-day",
    ],
    policyAreas: [
      "science, technology, communications",
      "government operations and politics",
      "armed forces and national security",
    ],
  },
  {
    categoryId: "POLICING_VIOLENT_CRIME",
    keywords: [
      "clearance rate",
      "cold case",
      "cold case investigation",
      "crime lab",
      "crime laboratory",
      "crime victim",
      "domestic violence",
      "fbi",
      "federal bureau of investigation",
      "forensic",
      "forensic evidence",
      "forensic science",
      "gun violence",
      "homicide",
      "homicide investigation",
      "human trafficking",
      "murder",
      "rape kit",
      "sexual assault kit",
      "solve rate",
      "victim services",
      "violent crime",
      "violent crime reduction",
      "violent offender",
    ],
    policyAreas: ["crime and law enforcement"],
  },
] as const;
