/**
 * Client-side TTS helper for the demo player.
 *
 * Priority:
 *   1. Narration manifest (pre-generated MP3s in /audio/narration/)
 *   2. Legacy pre-generated WAV (/demo-audio/)
 *   3. Real-time Gemini TTS API
 *   4. Subtitle-only (graceful degradation)
 *
 * Returns both an HTMLAudioElement and an AnalyserNode for lip-sync.
 */

export interface DemoAudioResult {
  audio: HTMLAudioElement;
  analyser: AnalyserNode;
}

const audioCache = new Map<string, DemoAudioResult>();
/** Track which text hash was cached per key, so hot-reload text changes bust the cache */
const cacheTextHash = new Map<string, number>();

function simpleHash(str: string): number {
  let h = 0;
  for (let i = 0; i < str.length; i++) {
    h = (Math.imul(31, h) + str.charCodeAt(i)) | 0;
  }
  return h;
}

// Shared AudioContext — reused across slides (browsers limit creation)
let sharedCtx: AudioContext | null = null;

function getAudioContext(): AudioContext {
  if (!sharedCtx) {
    sharedCtx = new AudioContext();
  }
  if (sharedCtx.state === "suspended") {
    sharedCtx.resume().catch(() => {});
  }
  return sharedCtx;
}

// ---------------------------------------------------------------------------
// Manifest-based lookup (MP3s generated by generate-narration script)
// ---------------------------------------------------------------------------

type ManifestEntry = { hash: string; file: string; generatedAt: string };
type Manifest = Record<string, ManifestEntry>;

let manifestPromise: Promise<Manifest | null> | null = null;

function getManifest(): Promise<Manifest | null> {
  if (!manifestPromise) {
    manifestPromise = fetch("/audio/narration/manifest.json")
      .then((r) => (r.ok ? r.json() : null))
      .catch(() => null);
  }
  return manifestPromise;
}

/** Try to load from the narration manifest (MP3 files) */
async function tryManifest(slideId: string): Promise<HTMLAudioElement | null> {
  const manifest = await getManifest();
  if (!manifest) return null;

  const keysToTry = [slideId];

  if (segmentToSlideId[slideId]) {
    const gameSlideId = segmentToSlideId[slideId];
    keysToTry.push(`protocol-labs--${gameSlideId}`, gameSlideId);
  }

  for (const key of keysToTry) {
    const entry = manifest[key];
    if (entry) {
      return loadAudio(`/audio/narration/${entry.file}`);
    }
  }

  return null;
}

/**
 * Maps segment IDs to game slide IDs for manifest lookup.
 */
export const segmentToSlideId: Record<string, string> = {
  // pl-* segments that have unique manifest keys (no script-* collision)
  "pl-170t": "military-waste-170t",
  "pl-game": "one-percent-referendum-vote",
  "pl-prize": "dominant-assurance-contract",
  "pl-fund": "three-scenarios-all-win",
  "pl-budget": "eigenvector-budget-result",
  "pl-armory": "armory",
  "pl-dirs": "decentralized-irs",
  "pl-dwelfare": "decentralized-welfare",
  "pl-dfed": "decentralized-federal-reserve",
  "pl-targets": "win-conditions-hale-income",
  "pl-ignorance": "pluralistic-ignorance-bug",
  "pl-170t-cost": "170t-opportunity-cost",
  "pl-opg": "optimal-policy-generator",
  "pl-obg": "optimal-budget-generator",
  "pl-cta": "post-credits-aliens",
  // script-* segments
  "script-1a-misaligned": "misaligned-superintelligence",
  "script-1b-objective": "earth-optimization-game",
  "script-2a-deaths": "daily-death-toll",
  "script-2b-ratio": "military-health-ratio",
  "script-3a-moronia": "game-over-moronia",
  "script-3b-wishonia": "restore-from-wishonia",
  "script-4a-fix": "one-percent-treaty",
  "script-4b-acceleration": "trial-acceleration-12x",
  "script-armory-dfda": "decentralized-fda",
  "script-armory-iab": "incentive-alignment-bonds",
  "script-armory-superpac": "smart-contract-superpac",
  "script-armory-storacha": "ipfs-immutable-storage",
  "script-armory-hypercerts": "impact-certificates",
  "script-10b-lives": "ten-billion-lives-saved",
  "script-11-close": "final-call-to-action",
};

// ---------------------------------------------------------------------------
// Real-time TTS (non-streaming fallback)
// ---------------------------------------------------------------------------

async function generateRealTime(text: string): Promise<HTMLAudioElement | null> {
  try {
    const resp = await fetch("/api/demo/tts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text }),
    });

    if (!resp.ok) return null;

    const blob = await resp.blob();
    const url = URL.createObjectURL(blob);
    return loadAudio(url);
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Streaming TTS — browser starts playback as chunks arrive
// ---------------------------------------------------------------------------

function generateStreaming(text: string): Promise<HTMLAudioElement | null> {
  return new Promise((resolve) => {
    const url = `/api/demo/tts/stream?text=${encodeURIComponent(text)}`;
    const audio = new Audio(url);
    audio.crossOrigin = "anonymous";
    // Resolve on canplay (enough data to start) instead of canplaythrough
    audio.addEventListener("canplay", () => resolve(audio), { once: true });
    audio.addEventListener("error", () => resolve(null), { once: true });
  });
}

// ---------------------------------------------------------------------------
// Shared audio loader
// ---------------------------------------------------------------------------

function loadAudio(url: string): Promise<HTMLAudioElement | null> {
  return new Promise((resolve) => {
    const audio = new Audio(url);
    audio.crossOrigin = "anonymous";
    audio.addEventListener("canplaythrough", () => resolve(audio), { once: true });
    audio.addEventListener("error", () => resolve(null), { once: true });
  });
}

/**
 * Wire an HTMLAudioElement through Web Audio API to get an AnalyserNode.
 * createMediaElementSource can only be called once per element, so this
 * must happen before caching.
 */
function wireAnalyser(audio: HTMLAudioElement): AnalyserNode {
  const ctx = getAudioContext();
  // Resume context (required after user gesture)
  if (ctx.state === "suspended") {
    ctx.resume().catch(() => {});
  }
  const source = ctx.createMediaElementSource(audio);
  const analyser = ctx.createAnalyser();
  analyser.fftSize = 256;
  source.connect(analyser);
  analyser.connect(ctx.destination);
  return analyser;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Get audio + analyser for a demo slide. Returns null if TTS is unavailable.
 * Results are cached for the session.
 */
export async function getDemoAudio(
  slideId: string,
  narrationText: string,
  forceLive = false,
): Promise<DemoAudioResult | null> {
  const cacheKey = forceLive ? `${slideId}__live` : slideId;
  const textHash = simpleHash(narrationText);

  // Return cached if same key AND same text (bust cache on hot-reload text changes)
  if (audioCache.has(cacheKey) && cacheTextHash.get(cacheKey) === textHash) {
    const cached = audioCache.get(cacheKey)!;
    cached.audio.currentTime = 0;
    return cached;
  }

  // Force live: use streaming endpoint for instant playback start
  // Fallback chain: manifest MP3 → real-time TTS
  const audio = forceLive
    ? await generateStreaming(narrationText) ?? await generateRealTime(narrationText)
    : (await tryManifest(slideId)) ??
      (await generateRealTime(narrationText));

  if (audio) {
    const analyser = wireAnalyser(audio);
    const result = { audio, analyser };
    audioCache.set(cacheKey, result);
    cacheTextHash.set(cacheKey, textHash);
    return result;
  }
  return null;
}
