/**
 * Client-side TTS helper for the demo player.
 *
 * Priority:
 *   1. Narration manifest (pre-generated MP3s in /audio/narration/)
 *   2. Legacy pre-generated WAV (/demo-audio/)
 *   3. Real-time Gemini TTS API
 *   4. Subtitle-only (graceful degradation)
 *
 * Returns both an HTMLAudioElement and an AnalyserNode for lip-sync.
 */

export interface DemoAudioResult {
  audio: HTMLAudioElement;
  analyser: AnalyserNode;
}

const audioCache = new Map<string, DemoAudioResult>();

// Shared AudioContext — reused across slides (browsers limit creation)
let sharedCtx: AudioContext | null = null;

function getAudioContext(): AudioContext {
  if (!sharedCtx) {
    sharedCtx = new AudioContext();
  }
  if (sharedCtx.state === "suspended") {
    sharedCtx.resume().catch(() => {});
  }
  return sharedCtx;
}

// ---------------------------------------------------------------------------
// Manifest-based lookup (MP3s generated by generate-narration script)
// ---------------------------------------------------------------------------

type ManifestEntry = { hash: string; file: string; generatedAt: string };
type Manifest = Record<string, ManifestEntry>;

let manifestPromise: Promise<Manifest | null> | null = null;

function getManifest(): Promise<Manifest | null> {
  if (!manifestPromise) {
    manifestPromise = fetch("/audio/narration/manifest.json")
      .then((r) => (r.ok ? r.json() : null))
      .catch(() => null);
  }
  return manifestPromise;
}

/** Try to load from the narration manifest (MP3 files) */
async function tryManifest(slideId: string): Promise<HTMLAudioElement | null> {
  const manifest = await getManifest();
  if (!manifest) return null;

  const keysToTry = [slideId];

  if (segmentToSlideId[slideId]) {
    const gameSlideId = segmentToSlideId[slideId];
    keysToTry.push(`protocol-labs--${gameSlideId}`, gameSlideId);
  }

  for (const key of keysToTry) {
    const entry = manifest[key];
    if (entry) {
      return loadAudio(`/audio/narration/${entry.file}`);
    }
  }

  return null;
}

/**
 * Maps segment IDs to game slide IDs for manifest lookup.
 */
const segmentToSlideId: Record<string, string> = {
  "pl-intro": "earth-optimization-game",
  "pl-170t": "military-waste-170t",
  "pl-misaligned": "misaligned-superintelligence",
  "pl-ratio": "military-health-ratio",
  "pl-moronia": "game-over-moronia",
  "pl-wishonia": "restore-from-wishonia",
  "pl-treaty": "one-percent-treaty",
  "pl-game": "one-percent-referendum-vote",
  "pl-prize": "dominant-assurance-contract",
  "pl-dfda": "decentralized-fda",
  "pl-opg": "optimal-policy-generator",
  "pl-obg": "optimal-budget-generator",
  "pl-iab": "incentive-alignment-bonds",
  "pl-storacha": "ipfs-immutable-storage",
  "pl-hypercerts": "impact-certificates",
  "pl-lives": "ten-billion-lives-saved",
  "pl-close": "final-call-to-action",
  "pl-cta": "post-credits-aliens",
  "script-1a-misaligned": "misaligned-superintelligence",
  "script-1b-objective": "earth-optimization-game",
  "script-2a-deaths": "daily-death-toll",
  "script-2b-ratio": "military-health-ratio",
  "script-3a-moronia": "game-over-moronia",
  "script-3b-wishonia": "restore-from-wishonia",
  "script-4a-fix": "one-percent-treaty",
  "script-4b-acceleration": "trial-acceleration-12x",
  "script-armory-dfda": "decentralized-fda",
  "script-armory-iab": "incentive-alignment-bonds",
  "script-armory-superpac": "smart-contract-superpac",
  "script-armory-storacha": "ipfs-immutable-storage",
  "script-armory-hypercerts": "impact-certificates",
  "script-10b-lives": "ten-billion-lives-saved",
  "script-11-close": "final-call-to-action",
};

// ---------------------------------------------------------------------------
// Legacy WAV lookup
// ---------------------------------------------------------------------------

async function tryPreGenerated(slideId: string): Promise<HTMLAudioElement | null> {
  const url = `/demo-audio/${slideId}.wav`;
  try {
    const resp = await fetch(url, { method: "HEAD" });
    if (resp.ok) return loadAudio(url);
  } catch {
    // Pre-generated file doesn't exist
  }
  return null;
}

// ---------------------------------------------------------------------------
// Real-time TTS
// ---------------------------------------------------------------------------

async function generateRealTime(text: string): Promise<HTMLAudioElement | null> {
  try {
    const resp = await fetch("/api/demo/tts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text }),
    });

    if (!resp.ok) return null;

    const blob = await resp.blob();
    const url = URL.createObjectURL(blob);
    return loadAudio(url);
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Shared audio loader
// ---------------------------------------------------------------------------

function loadAudio(url: string): Promise<HTMLAudioElement | null> {
  return new Promise((resolve) => {
    const audio = new Audio(url);
    audio.crossOrigin = "anonymous";
    audio.addEventListener("canplaythrough", () => resolve(audio), { once: true });
    audio.addEventListener("error", () => resolve(null), { once: true });
  });
}

/**
 * Wire an HTMLAudioElement through Web Audio API to get an AnalyserNode.
 * createMediaElementSource can only be called once per element, so this
 * must happen before caching.
 */
function wireAnalyser(audio: HTMLAudioElement): AnalyserNode {
  const ctx = getAudioContext();
  // Resume context (required after user gesture)
  if (ctx.state === "suspended") {
    ctx.resume().catch(() => {});
  }
  const source = ctx.createMediaElementSource(audio);
  const analyser = ctx.createAnalyser();
  analyser.fftSize = 256;
  source.connect(analyser);
  analyser.connect(ctx.destination);
  return analyser;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Get audio + analyser for a demo slide. Returns null if TTS is unavailable.
 * Results are cached for the session.
 */
export async function getDemoAudio(
  slideId: string,
  narrationText: string,
): Promise<DemoAudioResult | null> {
  if (audioCache.has(slideId)) {
    const cached = audioCache.get(slideId)!;
    cached.audio.currentTime = 0;
    return cached;
  }

  // Try manifest MP3 → legacy WAV → real-time TTS
  const audio =
    (await tryManifest(slideId)) ??
    (await tryPreGenerated(slideId)) ??
    (await generateRealTime(narrationText));

  if (audio) {
    const analyser = wireAnalyser(audio);
    const result = { audio, analyser };
    audioCache.set(slideId, result);
    return result;
  }
  return null;
}
