ALTER TYPE "OrgType" ADD VALUE IF NOT EXISTS 'GOVERNMENT';
ALTER TYPE "OrgType" ADD VALUE IF NOT EXISTS 'COMPANY';
ALTER TYPE "OrgType" ADD VALUE IF NOT EXISTS 'FOUNDATION';
ALTER TYPE "OrgType" ADD VALUE IF NOT EXISTS 'INTERGOVERNMENTAL';
ALTER TYPE "OrgType" ADD VALUE IF NOT EXISTS 'MEDIA';
ALTER TYPE "OrgType" ADD VALUE IF NOT EXISTS 'POLITICAL_PARTY';
ALTER TYPE "OrgType" ADD VALUE IF NOT EXISTS 'OTHER';

ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "sourceUrl" TEXT;
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "sourceRef" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "Organization_sourceRef_key" ON "Organization"("sourceRef");
CREATE INDEX IF NOT EXISTS "Organization_deletedAt_idx" ON "Organization"("deletedAt");

DO $$ BEGIN
  ALTER TABLE "Task" RENAME COLUMN "officeTitle" TO "roleTitle";
EXCEPTION WHEN undefined_column THEN NULL;
END $$;

ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "assigneeOrganizationId" TEXT;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "dueAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "Task_assigneeOrganizationId_idx" ON "Task"("assigneeOrganizationId");
CREATE INDEX IF NOT EXISTS "Task_dueAt_idx" ON "Task"("dueAt");

DO $$ BEGIN
  ALTER TABLE "Task" ADD CONSTRAINT "Task_assigneeOrganizationId_fkey"
  FOREIGN KEY ("assigneeOrganizationId") REFERENCES "Organization"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
