// Auto-generated by generate-web-data.ts — do not edit manually.
// Regenerate with: pnpm --filter @optimitron/web run generate
import type { PolicyReportJSON } from "@optimitron/opg";

export const usPolicyAnalysis: PolicyReportJSON = {
  "jurisdiction": "United States",
  "policies": [
    {
      "name": "Universal Pre-K (Ages 3-4)",
      "type": "budget_allocation",
      "category": "education",
      "description": "Federally funded universal pre-K. Perry Preschool RCT shows $7-12 ROI per dollar over 40 years.",
      "recommendationType": "reallocate",
      "evidenceGrade": "A",
      "causalConfidenceScore": 0.884,
      "policyImpactScore": 0.683,
      "welfareScore": 38,
      "incomeEffect": 0.15,
      "healthEffect": 0.1,
      "bradfordHillScores": {
        "strength": 0.931,
        "consistency": 0.918,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 1,
        "plausibility": 1,
        "coherence": 0.993,
        "analogy": 0.85,
        "specificity": 0.358
      },
      "rationale": "Perry Preschool RCT: 40-year follow-up shows $7-12 ROI per dollar. Participants had 15% higher income, 20% less likely to be arrested, healthier outcomes. France, Denmark, Finland all have universal pre-K with better PISA scores.",
      "currentStatus": "Only 34% of US 3-year-olds enrolled; varies wildly by state",
      "recommendedTarget": "Federal funding for universal enrollment by age 3",
      "blockingFactors": [
        "budget_constraint"
      ]
    },
    {
      "name": "Pragmatic Clinical Trial Funding Reform",
      "type": "regulation",
      "category": "health_research",
      "description": "Redirect research funding to pragmatic real-world trials. UK NIHR produces actionable evidence at 1/10th the cost.",
      "recommendationType": "implement",
      "evidenceGrade": "A",
      "causalConfidenceScore": 0.801,
      "policyImpactScore": 0.637,
      "welfareScore": 39,
      "incomeEffect": 0.05,
      "healthEffect": 0.3,
      "bradfordHillScores": {
        "strength": 0.95,
        "consistency": 0.551,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 1,
        "plausibility": 1,
        "coherence": 0.798,
        "analogy": 0.85,
        "specificity": 0.419
      },
      "rationale": "NIH spends $48B/yr but 70%+ goes to indirect costs. 85% of findings fail to replicate. UK NIHR model: pragmatic trials embedded in NHS produce actionable evidence at 1/10th the cost. PCORI pragmatic trials show 3x faster clinical adoption.",
      "currentStatus": "NIH: $48B/yr, <10% on pragmatic trials, 85% of findings fail to replicate",
      "recommendedTarget": "Mandate 30%+ of research budget for pragmatic trials with open data requirements",
      "blockingFactors": [
        "institutional_resistance",
        "industry_resistance"
      ]
    },
    {
      "name": "Military: Adopt Switzerland's Approach",
      "type": "budget_allocation",
      "category": "military",
      "description": "Reduce military spending to the cheapest high-performer floor. Switzerland achieves Life Expectancy 83.37 at $389/cap; United States gets 76.93 at $2052/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.739,
      "policyImpactScore": 0.596,
      "welfareScore": 38,
      "incomeEffect": 0.408,
      "healthEffect": 0.049,
      "bradfordHillScores": {
        "strength": 0.971,
        "consistency": 0.939,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.996,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: Switzerland achieves Life Expectancy 83.37 at $389/cap. United States at $2052/cap (5.3x overspend). Top 3: Switzerland ($389), Japan ($400), Sweden ($565). Savings: $564B/yr → $4,240/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $2052/cap, ranks 27/28. 5.3x overspend.",
      "recommendedTarget": "Switzerland model ($389/cap floor). $564B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Homeland Security: Adopt Switzerland's Approach",
      "type": "budget_allocation",
      "category": "homeland_security",
      "description": "Reduce homeland security spending to the cheapest high-performer floor. Switzerland achieves Life Expectancy 83.37 at $389/cap; United States gets 76.93 at $2052/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.739,
      "policyImpactScore": 0.596,
      "welfareScore": 38,
      "incomeEffect": 0.408,
      "healthEffect": 0.049,
      "bradfordHillScores": {
        "strength": 0.971,
        "consistency": 0.939,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.996,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: Switzerland achieves Life Expectancy 83.37 at $389/cap. United States at $2052/cap (5.3x overspend). Top 3: Switzerland ($389), Japan ($400), Sweden ($565). Savings: $564B/yr → $4,240/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $2052/cap, ranks 27/28. 5.3x overspend.",
      "recommendedTarget": "Switzerland model ($389/cap floor). $564B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Veterans Affairs: Adopt South Korea's Approach",
      "type": "budget_allocation",
      "category": "veterans_affairs",
      "description": "Reduce veterans affairs spending to the cheapest high-performer floor. South Korea achieves Life Expectancy 83.57 at $3588/cap; United States gets 76.93 at $10333/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.722,
      "policyImpactScore": 0.591,
      "welfareScore": 39,
      "incomeEffect": 1.656,
      "healthEffect": 0.05,
      "bradfordHillScores": {
        "strength": 0.855,
        "consistency": 0.939,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.996,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: South Korea achieves Life Expectancy 83.57 at $3588/cap. United States at $10333/cap (2.9x overspend). Top 3: South Korea ($3588), Japan ($4095), Australia ($4544). Savings: $2287B/yr → $17,192/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $10333/cap, ranks 28/28. 2.9x overspend.",
      "recommendedTarget": "South Korea model ($3588/cap floor). $2287B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Health (non-Medicare/Medicaid): Adopt South Korea's Approach",
      "type": "budget_allocation",
      "category": "health_non_medicare_medicaid_",
      "description": "Reduce health (non-medicare/medicaid) spending to the cheapest high-performer floor. South Korea achieves Life Expectancy 83.57 at $3588/cap; United States gets 76.93 at $10333/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.722,
      "policyImpactScore": 0.591,
      "welfareScore": 39,
      "incomeEffect": 1.656,
      "healthEffect": 0.05,
      "bradfordHillScores": {
        "strength": 0.855,
        "consistency": 0.939,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.996,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: South Korea achieves Life Expectancy 83.57 at $3588/cap. United States at $10333/cap (2.9x overspend). Top 3: South Korea ($3588), Japan ($4095), Australia ($4544). Savings: $2287B/yr → $17,192/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $10333/cap, ranks 28/28. 2.9x overspend.",
      "recommendedTarget": "South Korea model ($3588/cap floor). $2287B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Justice / Law Enforcement: Adopt South Korea's Approach",
      "type": "budget_allocation",
      "category": "justice_law_enforcement",
      "description": "Reduce justice / law enforcement spending to the cheapest high-performer floor. South Korea achieves Life Expectancy 83.57 at $6037/cap; United States gets 76.93 at $12848/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.704,
      "policyImpactScore": 0.58,
      "welfareScore": 39,
      "incomeEffect": 1.672,
      "healthEffect": 0.05,
      "bradfordHillScores": {
        "strength": 0.753,
        "consistency": 0.926,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.994,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: South Korea achieves Life Expectancy 83.57 at $6037/cap. United States at $12848/cap (2.1x overspend). Top 3: South Korea ($6037), Singapore ($7868), Australia ($8330). Savings: $2309B/yr → $17,361/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $12848/cap, ranks 25/26. 2.1x overspend.",
      "recommendedTarget": "South Korea model ($6037/cap floor). $2309B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "EPA / Environment: Adopt South Korea's Approach",
      "type": "budget_allocation",
      "category": "epa_environment",
      "description": "Reduce epa / environment spending to the cheapest high-performer floor. South Korea achieves Life Expectancy 83.57 at $6037/cap; United States gets 76.93 at $12848/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.704,
      "policyImpactScore": 0.58,
      "welfareScore": 39,
      "incomeEffect": 1.672,
      "healthEffect": 0.05,
      "bradfordHillScores": {
        "strength": 0.753,
        "consistency": 0.926,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.994,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: South Korea achieves Life Expectancy 83.57 at $6037/cap. United States at $12848/cap (2.1x overspend). Top 3: South Korea ($6037), Singapore ($7868), Australia ($8330). Savings: $2309B/yr → $17,361/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $12848/cap, ranks 25/26. 2.1x overspend.",
      "recommendedTarget": "South Korea model ($6037/cap floor). $2309B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Shift Drug Policy from Criminal to Health Approach",
      "type": "regulation",
      "category": "health",
      "description": "Decriminalize personal drug use, redirect enforcement budget to treatment. Based on Portugal (2001).",
      "recommendationType": "implement",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.695,
      "policyImpactScore": 0.574,
      "welfareScore": 39,
      "incomeEffect": 0.05,
      "healthEffect": 0.35,
      "bradfordHillScores": {
        "strength": 0.982,
        "consistency": 0.777,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.95,
        "analogy": 0.85,
        "specificity": 0.419
      },
      "rationale": "Portugal decriminalized in 2001: drug deaths dropped 80%, HIV among users dropped 90%, treatment uptake tripled. US spends $40B/yr on drug enforcement with zero measurable reduction in drug deaths (r=0.026). Czech Republic, Switzerland, Netherlands show similar results.",
      "currentStatus": "US spends $40B/yr on enforcement; 1.5M arrests/yr; overdose deaths at record highs",
      "recommendedTarget": "Decriminalize personal use, redirect enforcement budget to treatment",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Housing Supply Deregulation",
      "type": "regulation",
      "category": "housing",
      "description": "Remove restrictive zoning that constrains housing supply. Tokyo, Minneapolis, Oregon show reduced housing cost growth.",
      "recommendationType": "implement",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.683,
      "policyImpactScore": 0.561,
      "welfareScore": 38,
      "incomeEffect": 0.05,
      "healthEffect": 0.03,
      "bradfordHillScores": {
        "strength": 0.903,
        "consistency": 0.777,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.95,
        "analogy": 0.85,
        "specificity": 0.419
      },
      "rationale": "Tokyo has no housing crisis because they allow building. Minneapolis eliminated single-family zoning: rents stabilized. Oregon statewide upzoning reduced housing cost growth. Hsieh & Moretti (2019) estimate $1.6T/yr GDP cost from restrictive zoning.",
      "currentStatus": "75% of US residential land zoned single-family only",
      "recommendedTarget": "Condition federal grants on local zoning reform",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Energy: Adopt Netherlands's Approach",
      "type": "budget_allocation",
      "category": "energy",
      "description": "Reduce energy spending to the cheapest high-performer floor. Netherlands achieves After-Tax Median Income (PPP) 31221.39 at $1064/cap; United States gets 16287.22 at $1991/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.652,
      "policyImpactScore": 0.542,
      "welfareScore": 38,
      "incomeEffect": 0.228,
      "healthEffect": 0,
      "bradfordHillScores": {
        "strength": 0.718,
        "consistency": 0.939,
        "temporality": 1,
        "gradient": 0.265,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.996,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: Netherlands achieves After-Tax Median Income (PPP) 31221.39 at $1064/cap. United States at $1991/cap (1.9x overspend). Top 3: Netherlands ($1064), Norway ($1214), Denmark ($1317). Savings: $314B/yr → $2,363/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $1991/cap, ranks 25/28. 1.9x overspend.",
      "recommendedTarget": "Netherlands model ($1064/cap floor). $314B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Science / NASA: Adopt Netherlands's Approach",
      "type": "budget_allocation",
      "category": "science_nasa",
      "description": "Reduce science / nasa spending to the cheapest high-performer floor. Netherlands achieves After-Tax Median Income (PPP) 31221.39 at $1064/cap; United States gets 16287.22 at $1991/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.652,
      "policyImpactScore": 0.542,
      "welfareScore": 38,
      "incomeEffect": 0.228,
      "healthEffect": 0,
      "bradfordHillScores": {
        "strength": 0.718,
        "consistency": 0.939,
        "temporality": 1,
        "gradient": 0.265,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.996,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: Netherlands achieves After-Tax Median Income (PPP) 31221.39 at $1064/cap. United States at $1991/cap (1.9x overspend). Top 3: Netherlands ($1064), Norway ($1214), Denmark ($1317). Savings: $314B/yr → $2,363/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $1991/cap, ranks 25/28. 1.9x overspend.",
      "recommendedTarget": "Netherlands model ($1064/cap floor). $314B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Commerce / Economic Development: Adopt Netherlands's Approach",
      "type": "budget_allocation",
      "category": "commerce_economic_development",
      "description": "Reduce commerce / economic development spending to the cheapest high-performer floor. Netherlands achieves After-Tax Median Income (PPP) 31221.39 at $1064/cap; United States gets 16287.22 at $1991/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.652,
      "policyImpactScore": 0.542,
      "welfareScore": 38,
      "incomeEffect": 0.228,
      "healthEffect": 0,
      "bradfordHillScores": {
        "strength": 0.718,
        "consistency": 0.939,
        "temporality": 1,
        "gradient": 0.265,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.996,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: Netherlands achieves After-Tax Median Income (PPP) 31221.39 at $1064/cap. United States at $1991/cap (1.9x overspend). Top 3: Netherlands ($1064), Norway ($1214), Denmark ($1317). Savings: $314B/yr → $2,363/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $1991/cap, ranks 25/28. 1.9x overspend.",
      "recommendedTarget": "Netherlands model ($1064/cap floor). $314B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Education: Adopt Japan's Approach",
      "type": "budget_allocation",
      "category": "education",
      "description": "Reduce education spending to the cheapest high-performer floor. Japan achieves PISA Math Score 536 at $1288/cap; United States gets 465 at $2996/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.649,
      "policyImpactScore": 0.541,
      "welfareScore": 38,
      "incomeEffect": 0.419,
      "healthEffect": 0,
      "bradfordHillScores": {
        "strength": 0.784,
        "consistency": 0.667,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.889,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: Japan achieves PISA Math Score 536 at $1288/cap. United States at $2996/cap (2.3x overspend). Top 3: Japan ($1288), Taiwan ($1367), Singapore ($2509). Savings: $579B/yr → $4,353/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $2996/cap, ranks 11/11. 2.3x overspend.",
      "recommendedTarget": "Japan model ($1288/cap floor). $579B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Transportation: Adopt Singapore's Approach",
      "type": "budget_allocation",
      "category": "transportation",
      "description": "Reduce transportation spending to the cheapest high-performer floor. Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap; United States gets 16287.22 at $12848/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.639,
      "policyImpactScore": 0.539,
      "welfareScore": 39,
      "incomeEffect": 1.223,
      "healthEffect": 0,
      "bradfordHillScores": {
        "strength": 0.656,
        "consistency": 0.926,
        "temporality": 1,
        "gradient": 0.265,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.994,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap. United States at $12848/cap (1.6x overspend). Top 3: Singapore ($7868), Netherlands ($10605), Switzerland ($10699). Savings: $1688B/yr → $12,694/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $12848/cap, ranks 23/26. 1.6x overspend.",
      "recommendedTarget": "Singapore model ($7868/cap floor). $1688B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "HUD / Housing: Adopt Singapore's Approach",
      "type": "budget_allocation",
      "category": "hud_housing",
      "description": "Reduce hud / housing spending to the cheapest high-performer floor. Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap; United States gets 16287.22 at $12848/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.639,
      "policyImpactScore": 0.539,
      "welfareScore": 39,
      "incomeEffect": 1.223,
      "healthEffect": 0,
      "bradfordHillScores": {
        "strength": 0.656,
        "consistency": 0.926,
        "temporality": 1,
        "gradient": 0.265,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.994,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap. United States at $12848/cap (1.6x overspend). Top 3: Singapore ($7868), Netherlands ($10605), Switzerland ($10699). Savings: $1688B/yr → $12,694/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $12848/cap, ranks 23/26. 1.6x overspend.",
      "recommendedTarget": "Singapore model ($7868/cap floor). $1688B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Foreign Aid / International Affairs: Adopt Singapore's Approach",
      "type": "budget_allocation",
      "category": "foreign_aid_international_affairs",
      "description": "Reduce foreign aid / international affairs spending to the cheapest high-performer floor. Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap; United States gets 16287.22 at $12848/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.639,
      "policyImpactScore": 0.539,
      "welfareScore": 39,
      "incomeEffect": 1.223,
      "healthEffect": 0,
      "bradfordHillScores": {
        "strength": 0.656,
        "consistency": 0.926,
        "temporality": 1,
        "gradient": 0.265,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.994,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap. United States at $12848/cap (1.6x overspend). Top 3: Singapore ($7868), Netherlands ($10605), Switzerland ($10699). Savings: $1688B/yr → $12,694/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $12848/cap, ranks 23/26. 1.6x overspend.",
      "recommendedTarget": "Singapore model ($7868/cap floor). $1688B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Labor: Adopt Singapore's Approach",
      "type": "budget_allocation",
      "category": "labor",
      "description": "Reduce labor spending to the cheapest high-performer floor. Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap; United States gets 16287.22 at $12848/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.639,
      "policyImpactScore": 0.539,
      "welfareScore": 39,
      "incomeEffect": 1.223,
      "healthEffect": 0,
      "bradfordHillScores": {
        "strength": 0.656,
        "consistency": 0.926,
        "temporality": 1,
        "gradient": 0.265,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.994,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap. United States at $12848/cap (1.6x overspend). Top 3: Singapore ($7868), Netherlands ($10605), Switzerland ($10699). Savings: $1688B/yr → $12,694/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $12848/cap, ranks 23/26. 1.6x overspend.",
      "recommendedTarget": "Singapore model ($7868/cap floor). $1688B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Agriculture: Adopt Singapore's Approach",
      "type": "budget_allocation",
      "category": "agriculture",
      "description": "Reduce agriculture spending to the cheapest high-performer floor. Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap; United States gets 16287.22 at $12848/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.639,
      "policyImpactScore": 0.539,
      "welfareScore": 39,
      "incomeEffect": 1.223,
      "healthEffect": 0,
      "bradfordHillScores": {
        "strength": 0.656,
        "consistency": 0.926,
        "temporality": 1,
        "gradient": 0.265,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.994,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap. United States at $12848/cap (1.6x overspend). Top 3: Singapore ($7868), Netherlands ($10605), Switzerland ($10699). Savings: $1688B/yr → $12,694/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $12848/cap, ranks 23/26. 1.6x overspend.",
      "recommendedTarget": "Singapore model ($7868/cap floor). $1688B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Treasury / General Government: Adopt Singapore's Approach",
      "type": "budget_allocation",
      "category": "treasury_general_government",
      "description": "Reduce treasury / general government spending to the cheapest high-performer floor. Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap; United States gets 16287.22 at $12848/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.639,
      "policyImpactScore": 0.539,
      "welfareScore": 39,
      "incomeEffect": 1.223,
      "healthEffect": 0,
      "bradfordHillScores": {
        "strength": 0.656,
        "consistency": 0.926,
        "temporality": 1,
        "gradient": 0.265,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.994,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap. United States at $12848/cap (1.6x overspend). Top 3: Singapore ($7868), Netherlands ($10605), Switzerland ($10699). Savings: $1688B/yr → $12,694/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $12848/cap, ranks 23/26. 1.6x overspend.",
      "recommendedTarget": "Singapore model ($7868/cap floor). $1688B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "State Department / Diplomacy: Adopt Singapore's Approach",
      "type": "budget_allocation",
      "category": "state_department_diplomacy",
      "description": "Reduce state department / diplomacy spending to the cheapest high-performer floor. Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap; United States gets 16287.22 at $12848/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.639,
      "policyImpactScore": 0.539,
      "welfareScore": 39,
      "incomeEffect": 1.223,
      "healthEffect": 0,
      "bradfordHillScores": {
        "strength": 0.656,
        "consistency": 0.926,
        "temporality": 1,
        "gradient": 0.265,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.994,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap. United States at $12848/cap (1.6x overspend). Top 3: Singapore ($7868), Netherlands ($10605), Switzerland ($10699). Savings: $1688B/yr → $12,694/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $12848/cap, ranks 23/26. 1.6x overspend.",
      "recommendedTarget": "Singapore model ($7868/cap floor). $1688B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Interior / Natural Resources: Adopt Singapore's Approach",
      "type": "budget_allocation",
      "category": "interior_natural_resources",
      "description": "Reduce interior / natural resources spending to the cheapest high-performer floor. Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap; United States gets 16287.22 at $12848/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.639,
      "policyImpactScore": 0.539,
      "welfareScore": 39,
      "incomeEffect": 1.223,
      "healthEffect": 0,
      "bradfordHillScores": {
        "strength": 0.656,
        "consistency": 0.926,
        "temporality": 1,
        "gradient": 0.265,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.994,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis: Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap. United States at $12848/cap (1.6x overspend). Top 3: Singapore ($7868), Netherlands ($10605), Switzerland ($10699). Savings: $1688B/yr → $12,694/household/yr as Optimization Dividend.",
      "currentStatus": "United States spends $12848/cap, ranks 23/26. 1.6x overspend.",
      "recommendedTarget": "Singapore model ($7868/cap floor). $1688B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ]
    }
  ],
  "generatedAt": "2026-04-06T06:40:06.290Z",
  "generatedBy": "@optimitron/opg",
  "note": "Generated using Bradford Hill scoring and welfare calculation from real cross-country evidence."
};
